### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by sambit985** [sambit985/TicketManagementSystem#1]
**Create user interface for this TicketManagementSystem using ReactJS**
[https://github.com/sambit985/TicketManagementSystem](url)

Create UI as per above ☝️☝️☝️

**Comment by khushalmajoka** [comment]
is the issue been resolved? and if not assign it to me please I can do it.

**Comment by sambit985** [comment]
**

Thanks for your valuable comment but now this issue has resolved.

**

**Comment by sambit985** [comment]
@khushalmajoka You can work on LDTech-DevApp project. Many collaborators are working on that project. 

[Project Repo Link](https://github.com/sambit985/LdTech-DevApp )
